title: Are There Fecal Bacteria In Your NYC Water?
description: Using drinking water quality data, I hope to predict when there are coliform bacteria in your water based on water quality indicators. Coliform bacteria levels are an indicator of harmful bacteria in your water, and predictions can inform you when your water may be unsafe to drink.
